services:

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    restart: unless-stopped

    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production