name: Python Flask Application Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add your test commands here. For example:
        # pytest tests/

  ui-testing:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y chromium-browser

    - name: Run UI tests
      run: |
        # For UI tests, you might want to use something like Selenium
        # or a headless browser setup. For example, using a headless Chromium setup:
        chromium-browser --headless --disable-gpu --remote-debugging-port=9222 http://localhost:5000
        curl http://localhost:5000  # Ensure app is reachable
